### ISSUE TITLE
feature suggestion: only export items younger than a given timestamp

### ISSUE THREAD

**Issue by herrsimon** [tbvdm/sigtop#1]
Hello,

first of all thank you very much for the great program, it is multiple orders of magnitude faster than a python script with the same functionality I have been using so far. Could you please implement a timestamp option so that only messages and/or attachments younger than a given timestamp (either epoch or optionally human-readable) are exported? This would make cumulative backups much less cumbersome. 

Related, but not as important (at least for me): 

1. Could you please make the filename resolution logic configurable when exporting attachments, so that it is also possible to either overwrite existing files or only export attachments which are not already present in the filesystem (or let the user choose interactively, as is standard for cp)? The current behaviour of exporting everything again, possibly with some digit appended to the filename, is not very useful in my opinion.

2. Maybe it would be a good idea to optionally offer a more meaningful naming logic for exported attachments, for example by prepending the message timestamp formatted in a human-readable format (YYYY-MM-DD_HH_MM_SS). But this job is probably easier done in some post-processing script using python, Perl and the likes (of course sacrificing some speed).

**Comment by tbvdm** [comment]
> Could you please implement a timestamp option so that only messages and/or attachments younger than a given timestamp (either epoch or optionally human-readable) are exported? This would make cumulative backups much less cumbersome. 

I agree it would be useful to have options to select a subset of messages or attachments. Selection based on time, as you propose, would be one of those options. I'll look into it.

> 1. Could you please make the filename resolution logic configurable when exporting attachments, so that it is also possible to either overwrite existing files or only export attachments which are not already present in the filesystem (or let the user choose interactively, as is standard for cp)? The current behaviour of exporting everything again, possibly with some digit appended to the filename, is not very useful in my opinion.

When sigtop exports an attachment, it uses the attachment's original filename, if available. However, sometimes it happens that different attachments have the same original filename. In those cases, sigtop adds a sequence number to the filename.

For this reason, skipping or overwriting existing files is not straightforward. sigtop cannot tell if an existing file is an identical attachment from a previous export or a different attachment with the same filename.

As things stand, it's best to export attachments to an empty directory.

> 2. Maybe it would be a good idea to optionally offer a more meaningful naming logic for exported attachments, for example by prepending the message timestamp formatted in a human-readable format (YYYY-MM-DD_HH_MM_SS). But this job is probably easier done in some post-processing script using python, Perl and the likes (of course sacrificing some speed).

If the original filename for an attachment is not available, sigtop falls back to a hexadecimal string. I think you are referring to these hexadecimal filenames. I agree it would be better to fall back to a time-based name instead. I'll look into that, too.

**Comment by tbvdm** [comment]
> If the original filename for an attachment is not available, sigtop falls back to a hexadecimal string. I think you are referring to these hexadecimal filenames. I agree it would be better to fall back to a time-based name instead. I'll look into that, too.

I've just fixed this. Attachments (without original filename) now have filenames of the form "attachment-yyyy-mm-dd-hh-mm-ss.ext". Thanks.

**Comment by tbvdm** [comment]
> Could you please implement a timestamp option so that only messages and/or attachments younger than a given timestamp (either epoch or optionally human-readable) are exported? This would make cumulative backups much less cumbersome. 

@herrsimon I've added the -s option to the attachments and messages commands. See the manual for details. In your case, to export attachments sent at or after a given time, you'd use something like this (note the comma after the time):

sigtop attachments -s 2021-01-23T12:34:56, ~/.config/Signal

Does this work out for you?

**Comment by herrsimon** [comment]
Hi and sorry for this super late reply, I had a long-distance move, change of job and newborn kid to take care of (no joke). The -s option works like a charm, thanks a lot for implementing! One more thing to consider would be to (optionally) store or link attachments in subdirectories named after the phone number of the communication partner. This would make it much easier to find them afterwards ("where is that picture I sent to my spouse?"). This is of course not essential but would be a nice addon. Thanks again and have a nice weekend!

**Comment by tbvdm** [comment]
> Hi and sorry for this super late reply, I had a long-distance move, change of job and newborn kid to take care of (no joke).

No worries. And congratulations!

> The -s option works like a charm, thanks a lot for implementing!

Great!

> One more thing to consider would be to (optionally) store or link attachments in subdirectories named after the phone number of the communication partner. This would make it much easier to find them afterwards ("where is that picture I sent to my spouse?"). This is of course not essential but would be a nice addon.

I see what you mean. Yes, that seems useful. I'll look into it.

**Comment by tbvdm** [comment]
> One more thing to consider would be to (optionally) store or link attachments in subdirectories named after the phone number of the communication partner.

Hi. At long last, this has been implemented.
