### ISSUE TITLE
Incremental backup

### ISSUE THREAD

**Issue by corbolais** [tbvdm/sigtop#12]
Hi!

Thank you for sigtop, it's working great!

I've hacked up a shell script to implement an incremental backup, run by crontab.

Once finalized, I could post it here. But are you planning on extending sigtop to provide means to do incremental backups? [FeatureRequest] ;)

Cheers!

**Comment by tbvdm** [comment]
Hi @corbolais,

sigtop has basic support for incremental backups via the `-s` option. It would be nice to have a more streamlined implementation, but I don't know when I'll be able to look into that.

Feel free to post your script here. Maybe it will be useful to other people, too.
