### ISSUE TITLE
Import backup into Signal desktop

### ISSUE THREAD

**Issue by niklasravnsborg** [tbvdm/sigtop#14]
I'm looking into merging two backups of the `~Library/Application Support/Signal` folder into one. I didn't find a way to do it after messing with some importing/exporting in the two SQLite files. I'm able to successfully join the tables in the database, but it seems as there is some check hindering me to merge the message histories.

So my thinking now is to use a tool like this to export the data, and then maybe there is a simple way to import the backup back into the Desktop app.

I stumbled upon sigtop because I want to save some conversation data have after an unfortunate data loss. Thanks for your work.

**Comment by tbvdm** [comment]
I'm not familiar enough with Signal Desktop internals to say if and how two databases could be merged in a way that won't break things. Personally, I wouldn't try to make changes to the database unless I understood those changes.

Also, bear in mind that a faulty merge doesn't have to be noticeable right away. It might be that problems will show up only later, when triggered by a certain event. I honestly don't know.

The other route you're considering (importing data) would be sensitive to the same concerns.

I'm sorry I can't be of more help!
