### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by dotlambda** [tbvdm/sigtop#16]
In order for sigtop to be packaged by distributions, it would be nice if you could tag a release once in a while. Adding a changelog would be extra nice.

**Comment by tbvdm** [comment]
If it makes things easier for packagers, I'd be happy to tag, somewhat arbitrarily, a release every now and then. But is there an actual problem you're running into? If possible, just use the latest commit.

As for a changelog, couldn't you simply look at the commit log? sigtop is a simple project with a modest stream of commits. I don't think a changelog could offer more than the commit log already does.
