### ISSUE TITLE
linking messages to attachments?

### ISSUE THREAD

**Issue by gratefulfrog** [tbvdm/sigtop#17]
Hi,
Thanks for a great tool.
Just one question. I see no way to connect the extracted messages to their corresponding attachments? Is that the case?

One other question would it be possible to select the conversations we want to extract?

Thanks for a great tool!
Bob

**Comment by tbvdm** [comment]
Hi Bob,

I see what you mean. Yes, HTML output would make viewing attachments much more convenient. It's already on my todo list, but I don't know when I'll have the opportunity to spend time on it.

Thanks for your kind words. :)

**Comment by gratefulfrog** [comment]
Hi!

Did you implement the html? I would be happy to test it!
