### ISSUE TITLE
sigtop: invalid mention

### ISSUE THREAD

**Issue by nep2ner** [tbvdm/sigtop#20]
What does this output mean? After running the command below, there are text files written to `~/Signal-Export/messages`

I just want to make sure that it's not skipping anything. 

Command: `./sigtop export-messages ~/Signal-Export/messages`

Output:
```
sigtop: invalid mention
sigtop: open Unknown (group).txt: file exists
```

**Comment by nep2ner** [comment]
I narrowed the time frame to only the time I needed using `-s` and no longer received the error. This is no longer an issue for me, but I will leave it open in case it's helpful in some way.

**Comment by tbvdm** [comment]
It seems you have run into two separate issues. One could be similar to #19. If you're willing to do a few tests to help me investigate, let me know.
