### ISSUE TITLE
sigtop msg - Time

### ISSUE THREAD

**Issue by Tipograf** [tbvdm/sigtop#21]
sigtop msg -s 2023-04-25T00:00:00 newmsg

Dont generate any files

Tnks

**Comment by tbvdm** [comment]
What are you trying to do?

**Comment by Tipograf** [comment]
I want sigtop to save only those data from chats that were sent after, for example, 04/25/2023

**Comment by Tipograf** [comment]
And comand

"Export all attachments sent at or after 12:34:56 on 25 April 2023 to the directory attachments:

sigtop att -s 2023-04-25T12:34:56, attachments"

dont work

**Comment by tbvdm** [comment]
> I want sigtop to save only those data from chats that were sent after, for example, 04/25/2023

You need to add a comma after the date/time:

```
sigtop msg -s 2023-04-25T00:00:00, newmsg
```

> And comand
>
> "Export all attachments sent at or after 12:34:56 on 25 April 2023 to the directory attachments:
>
> sigtop att -s 2023-04-25T12:34:56, attachments"
>
> dont work

If you'd like me to help you with that, you'll have to be more specific.

**Comment by Tipograf** [comment]
I'm sorry, my English is not very good))
I want Sigtop to extract only those messages that were created after a certain date.
When I type "sigtop msg -s 2023-04-30T07:00:00, messages", I get an empty "messages" folder, no files

**Comment by tbvdm** [comment]
Are you sure you have messages that were sent after that time?

Please run:

```
sigtop msg -s 2023-04-30T07:00:00, msg-after
sigtop msg msg-all
for f in msg-all/*; do grep ^Sent: "$f" | tail -n1; done
```

Do you see times after 2023-04-30T07:00:00 in the output?

Is the `msg-after` directory empty?

**Comment by Tipograf** [comment]
[https://lh3.googleusercontent.com/gGQZB4b7WoU5Cq6rUf7FdYIjbUQTaIoFszj4Ckd9S76lF41T96tRyNdt1-AfWplbfLMO3Tu7hNtOlcyeeklL2hGVzLwV-wBiMJfcXRCOwB0Ucea-q70GVujeY0AxD_kEfLjVfViAjrO9BVyUrCYCL6ATEBkxAbiFWiZAKNcfbIWT2uC6Nn3tlszUu_1FclxOJ2wdd1AZsza9I3wB5EuLujuZ5RADv2KMgCcOWxCzOf7S9F6TZ80Alx7Dn_KmmCYJpgfwinPAdJySzvnkMv9ixPEUetA0r3QKUA_hfP6L8g0Aj-p_nY4Vum-RkAB91-vDDEf4DNDNaW_dDh3CP-qQbufiM_vQG7pTjQZm5HU5gfWZ_lpSdyRA4H3yvWLvl6-SyA3YdK0Hj3mMTJhjGqi9bNnbUPUNPy8jOlyMEraKkGTQePoId22owdCRNpQEGDbRrxhwHCxXvp3elusNgforxrfYDTzuldg9Irm1KESA_XSYJaiCTqS54oTqN0FRmIE-PJuFwAkgVHUl2r8W1FjXAhxrsB24hdGvTJUXgh175X7SRGockOWq1MXOsBENNANgLL1aOcuAy-UM_hLkkjFG5CfQ_fWJGHEQ7lt2YrslY-Ms76j8JNQdZlEGMROjfBhu8igBiWv-qouJ5PHT5QNmiKV789Jr3WzHJ4bj9qtdRF775kS2GOPDSOLlytDBH7JaIWtZoBV5Bwfn2iRLSQgbYLjZFxfekC92nazW1KuLba7QT-oygJlkX72bX1NcG7IO0YVQimMe0ge84a4ipZ2uvWWuPhRII6hG8lyZ3hex7yDbbpam-XENxszsRcHuHHTCm2u68uiCtU02D3gLA0kyks_PgOpIVS4LpjQobXI5NstERSaKR-oAWhpHesfbVYjJMbcawvtPtPlA_LDCC05NV0Ax39t-ShInJXEO6zhvSJl28FIJ=w1745-h729-s-no?authuser=0](url)

**Comment by Tipograf** [comment]
https://ibb.co/XSMCQ7X 
msg-after directory empty

**Comment by tbvdm** [comment]
I think I know what the problem is. I'll commit a fix soon.
