### ISSUE TITLE
database version 11 not supported (yet) [Session]

### ISSUE THREAD

**Issue by mdPlusPlus** [tbvdm/sigtop#22]
I'm trying to decrypt the database of a Signal fork (Session: https://github.com/oxen-io/session-desktop), unfortunately I'm met with this error:

`sigtop: database version 11 not supported (yet)`

Any idea what I could do about this?  
Which database version is Signal currently using?

**Edit**: Never mind, commenting out these lines works for supporting Session: https://github.com/tbvdm/sigtop/blob/718cd9fa9245602396949d24a5dae835eae39cf6/signal/open.go#L74-L77

Unfortunately it doesn't work with attachments, since Session is encrypting those too while Signal does not.

```
$ ~/go/bin/sigtop export-attachments -d /db/Session/ /db/Session/attachments
sigtop: cannot prepare statement: no such column: name
```

**Comment by tbvdm** [comment]
I don't know much about Session, but it seems it has diverged from Signal quite a bit. The problem you're running into now ("no such column: name") is that Session uses a different database schema. If you're interested in using sigtop to export from Session, I think you would first have to identify the changes between the two database schemas and see if it's feasible to accommodate these changes in sigtop.
