### ISSUE TITLE
Adding an option to export messages without some fields

### ISSUE THREAD

**Issue by letrollpoilu** [tbvdm/sigtop#25]
Hi there,

Your module is awesome I love it! I could export in an easy way precious data for me!

I just had a suggestion for improvement, to export the messages without some of the fields:
"Type"
"Sent"
"Received"

And maybe add extra spacing after a message and the "from", like 2 lines of space so that we can properly read the data, even in a text file.

Thank you so much for your work!

**Comment by tbvdm** [comment]
Thank you very much!

Regarding your suggestion, why do you want to omit those fields? I don't see how that would be an improvement.

The same goes for the extra newlines. Why is one empty line between messages not sufficient?

**Comment by letrollpoilu** [comment]
It's simply to make it more readable on a text file, to have less information and more spacing to read it as a conversation.

**Comment by tbvdm** [comment]
I could add a compact format that shows every message on a single line. Perhaps something like this:

```
2023-01-23 12:34 Alice: Bob always speaks the truth
2023-01-23 12:35 Bob: Everything Alice says is false
```

Would that help you?

**Comment by letrollpoilu** [comment]
Yes something like that would be awesome, with a blank line between the messages :) Thank you so much !

```
2023-01-23 12:34 Alice: Bob always speaks the truth

2023-01-23 12:35 Bob: Everything Alice says is false
```

**Comment by tbvdm** [comment]
Sorry for the late response. I'll try to add this soon.

**Comment by tbvdm** [comment]
I've added the `text-short` format. To use it, run something like this:

```
sigtop msg -f text-short
```

I decided not to include the blank lines. Sorry.

**Comment by letrollpoilu** [comment]
Super thank you very much!
