### ISSUE TITLE
Database export failing

### ISSUE THREAD

**Issue by letrollpoilu** [tbvdm/sigtop#26]
Hi again :)

I tried to export the Signal Desktop database in an SQL file, but I actually have a binary file, impossible to treat.

I used sigtop export-database signal.sql

Let me know if I did something wrong

**Comment by tbvdm** [comment]
The `export-database` command creates an SQLite database, which is a binary file. You can open this database with the `sqlite3` utility, or with `sqlitebrowser` if you prefer a GUI. You can also use `sqlite3` to export the database to several plain-text formats, such as CSV or raw SQL.

**Comment by letrollpoilu** [comment]
Thank you for your help. I was trying to open it with sqlitebrowser with the GUI and it didn't work saying that this wasn't a database file.

Now if I run:
export-database -d $HOME/.config/Signal signal.db
sqlitebrowser signal.db

I have this error:
malformed database schema (messages_on_delete) - no such table: main.messages

Do you have an idea of what it can be?

**Comment by tbvdm** [comment]
It appears the exported database is corrupt. The question is: is the Signal Desktop database itself corrupt or is there a bug in the export process?

Was Signal Desktop running when you exported the database?

Could you run the following commands and paste the output:

```
sigtop check
sigtop query 'pragma user_version'
sigtop query 'select name, type from sqlite_schema where tbl_name = "messages"'
```

Also, please install the `sqlite3` utility if you haven't already. Then run these commands and paste the output:

```
sigtop db signal.db
sqlite3 signal.db 'pragma integrity_check'
sqlite3 signal.db 'select name, type from sqlite_schema where tbl_name = "messages"'
```

**Comment by tbvdm** [comment]
Did you also run `sigtop check`?

Please run the following commands and paste the output (`signal.db` is the database you exported earlier):

```
sqlite3 -version
sqlite3 signal.db 'pragma integrity_check'
sqlite3 signal.db 'select name, type from sqlite_master where tbl_name = "messages"'
sqlite3 'select count(*) from messages'
```

If none those commands failed, try opening `signal.db` in sqlitebrowser.
