### ISSUE TITLE
can't install with goland

### ISSUE THREAD

**Issue by gratefulfrog** [tbvdm/sigtop#27]
Hi,
I pulled the most reccent github work and see that many things have changed!

I tried to follow the instructions on Xubuntu 18.04 and got :

`$ sudo apt-get install golang gcc
[sudo] password for bob: 

Reading package lists...
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
The following additional packages will be installed:
  golang-1.10 golang-1.10-doc golang-1.10-go golang-1.10-race-detector-runtime
  golang-1.10-src golang-doc golang-go golang-race-detector-runtime golang-src
Suggested packages:
  bzr mercurial subversion
The following NEW packages will be installed:
  golang golang-1.10 golang-1.10-doc golang-1.10-go
  golang-1.10-race-detector-runtime golang-1.10-src golang-doc golang-go
  golang-race-detector-runtime golang-src
0 upgraded, 10 newly installed, 0 to remove and 1 not upgraded.
Need to get 42.7 MB of archives.
After this operation, 229 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
...`

Worked fine, but then:
`$ sudo go install github.com/tbvdm/sigtop@master
can't load package: package github.com/tbvdm/sigtop@master: cannot find package "github.com/tbvdm/sigtop@master" in any of:
	/usr/lib/go-1.10/src/github.com/tbvdm/sigtop@master (from $GOROOT)
	/home/bob/go/src/github.com/tbvdm/sigtop@master (from $GOPATH)
`

I am sure that there is some detail I am not grasping...

Cheers,
Bob

**Comment by gratefulfrog** [comment]
I guess my system doesn't support above go 1.10 ...

**Comment by tbvdm** [comment]
You need Go 1.18 or later. On older Ubuntu releases you could install the latest Go version from go.dev or from a PPA. See e.g. https://zchee.github.io/golang-wiki/Ubuntu/ for more information.
