### ISSUE TITLE
Unable to map attachments in text with file attachments

### ISSUE THREAD

**Issue by valentinafeve** [tbvdm/sigtop#28]
I have been using your module and it has helped me a lot with my Machine Learning projects. I have noted that the attachments in the messages look like this: Attachment: no filename (audio/aac, 1248473 bytes) but in the files they may have a name related with its date or just something like 'image-XX' 

It makes the mapping between attachments and messages really difficult and I wonder if there's any reason why attachments cannot be more easily mapped?  

Thank you for your work!

**Comment by tbvdm** [comment]
I'm not sure I understand why you say it's difficult. Does [this comment](https://github.com/tbvdm/sigtop/issues/17#issuecomment-1453496272) clarify things for you?

But that's not to say the mapping can't be improved. If you have ideas for that, let me know.
