### ISSUE TITLE
Сannot find mention recipient for UUID ""

### ISSUE THREAD

**Issue by Tipograf** [tbvdm/sigtop#29]
Sigtop при єкспорті почав видавати помилки "cannot find mention recipient for UUID ""

>> sigtop msg -s 2023-07-10T00:00:00,2023-07-18T23:59:59 -d 'C:\Users\Admin\AppData\Roaming\Signal' -i -f json "C:\temp\Output"
>> sigtop msg -s 2023-07-10T00:00:00,2023-07-18T23:59:59 -d 'C:\Users\Admin\AppData\Roaming\Signal Beta' -i -f json "C:\temp\Output"
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: invalid mention (index: 1, body: 1348 2317, placeholders:, mentions: 0:230,8 1:126,20)
sigtop.exe: message with invalid mention (conversation: "***", sent: 2023-07-16 16:04:07)
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: invalid mention (index: 1, body: 1348 2317, placeholders:, mentions: 0:230,8 1:126,20)
sigtop.exe: message with invalid mention in quote (conversation: "***", sent: 2023-07-16 16:05:06)
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: invalid mention (index: 2, body: 74 132, placeholders: 0, mentions: 0:0,17 1:126,8 2:64,10 3:64,10)
sigtop.exe: message with invalid mention (conversation: "***", sent: 2023-07-17 20:39:04)
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""
sigtop.exe: cannot find mention recipient for UUID ""

**Comment by tbvdm** [comment]
This probably is text formatting, which sigtop does not yet support. I'll work on a fix.

**Comment by tbvdm** [comment]
I've committed a fix. If you still get errors, let me know.
