### ISSUE TITLE
cannot install on linux: "cannot use path@version syntax in GOPATH mode"

### ISSUE THREAD

**Issue by abadstart** [tbvdm/sigtop#35]
On Linux Mint 20.2

Both 
`go install github.com/tbvdm/sigtop@master`
and
`GOBIN=~/bin go install github.com/tbvdm/sigtop@master`

give the error:
`can't load package: package github.com/tbvdm/sigtop@master: cannot use path@version syntax in GOPATH mode`

How to proceed?

**Comment by tbvdm** [comment]
Your Go version is too old. It looks like you have the following options:

1. Upgrade your Linux distro.
2. Install Go from a PPA repository. See https://github.com/golang/go/wiki/Ubuntu#using-ppa.
3. Install a Go binary release directly from the Go project. See https://go.dev/doc/install.

**Comment by abadstart** [comment]
Installing Go from the PPA repo worked, thanks!
