### ISSUE TITLE
path_windows.go: sanitiseFilename is not robust

### ISSUE THREAD

**Issue by 3052** [tbvdm/sigtop#37]
this is not ideal:

https://github.com/tbvdm/sigtop/blob/0c7a8fe0d06b0b9b4f5512ddd997ca34a71543db/path_windows.go#L56

as any invalid UTF-8 justs get swapped for the unicode replacement character:

~~~go
runes := []rune("\xA0\xA1") // [fffd fffd]
~~~

and since that character is not a control character, it would just wind up in the resulting file name as is.

**Comment by 3052** [comment]
because the replacement character is its own, valid character. so unless a user intentionally used that in the user name, then it should be replaced in the output

**Comment by tbvdm** [comment]
Again, why? You seem to assume that the output has to be unambiguous. But that's not a goal here.

**Comment by 3052** [comment]
because its a worse representation of the original input. if you were just wanting to replace invalid UTF-8 with replacement characters, you could just do this:

~~~
runes := []rune(name) 
~~~

but youre also replacing characters:

https://github.com/tbvdm/sigtop/blob/0c7a8fe0d06b0b9b4f5512ddd997ca34a71543db/path_windows.go#L58-L60

in which case the replacement character should also be replaced, to signify something is invalid in the original input. otherwise you cant disambiguate from an intentional replacement character and one resulting from invalid UTF-8

**Comment by tbvdm** [comment]
> otherwise you cant disambiguate

As I've already told you, unambiguity is not a goal. That would require modifying valid filenames, too. I don't want to do that.

**Comment by 3052** [comment]
> That would require modifying valid filenames, too.

how is that? my suggestion would only impact input that contains invalid UTF-8

**Comment by tbvdm** [comment]
Suppose `f` is an invalid filename. Let `g := sanitiseFilename(f)`. Valid filenames are not to be modified, so `sanitiseFilename(g) == g`. Therefore, `sanitiseFilename(f) == sanitiseFilename(g)`, even though `f != g`.

**Comment by 3052** [comment]
I dont see how that answers the question. a filename with invalid UTF-8 is not valid, so would necessarily need replacement.

**Comment by tbvdm** [comment]
I'm very sorry, but I'm going to close this.

**Comment by 3052** [comment]
OK well I tried. if you have a justification why invalid UTF-8 is acceptable for a filename, I would be interested to hear it.
