### ISSUE TITLE
If I don't want to run sigtop on the production database of my signal desktop, how do I run it?

### ISSUE THREAD

**Issue by BlkPingu** [tbvdm/sigtop#38]
Can I copy attachments.noindex to desktop and run sigtop on it? Are there any caveats to doing so, meaning does sigtop require access to any of the SQL databases or other Signal files that it expects to be somewhere specifically relative to the target directory?

Please advise

**Comment by tbvdm** [comment]
You need to copy `attachments.noindex`, `config.json` and `sql`. It's a good idea to quit Signal Desktop first before copying. Use the `-d` option to point sigtop to the directory to which you copied the files.
