### ISSUE TITLE
Export to HTML and link attachments

### ISSUE THREAD

**Issue by vRobM** [tbvdm/sigtop#39]
Hello, love that this tool just works and the provided windows binaries!

One thing that is missing is HTML export so my non-tech friends can browse their chat history without parsing json or plain text, wondering what all the codes are for the emojis.

The implementation at https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#export-to-html seems to be nice output, hence I hope you can use it for sigtop.

Since sigtop does msg and att separately, is the way to do both with -i even though we're only doing it once (so far)?

The goal is to have the HTML output be more complete with images, a/v and other attachments linked inline.

Thanks!

**Comment by tbvdm** [comment]
> One thing that is missing is HTML export

Yes, that would be nice to have. It's on my to-do list!

> Since sigtop does msg and att separately, is the way to do both with -i even though we're only doing it once (so far)?

Sorry, I'm not sure I understand your question. Perhaps you could clarify?

**Comment by vRobM** [comment]
Excellent, can't wait to show it off to my lady for V day!

> Sorry, I'm not sure I understand your question. Perhaps you could clarify?

Yes, of course. As we are looking to HTML browse a conversation similar to how it's presented in Signal, I would want to run sigtop with exporting messages and attachments together. That way the HTML output is seamless, including dark mode.

So far in my testing, sigtop only seems to accept one of those parameters at a time, hence messages or attachments. And I'm not sure how well those merge afterward.

Hence the question about incremental mode and if it can pull both.

**Comment by vRobM** [comment]
Thank you for the heads up, much appreciated. I believe in miracles!

Excellent, thanks for clarifying. 

May the force be with you.

**Comment by bepaald** [comment]
I hope you don't mind me posting here. A user recently requested this feature of me, and I thought I remembered another project already providing this option. A quick search led me to this project, but after seeing the feature is not implemented here either I had a go myself. 

So it feels a bit weird to do this (maybe it's against GitHub-etiquette?, feel free to scold me or delete this message), but the original user hasn't responded and I could use some feedback/testers. So @vRobM: if you are interested, you could try the export-desktop-to-html feature and chime in on https://github.com/bepaald/signalbackup-tools/issues/203

Thanks!

**Comment by AkechiShiro** [comment]
Can this be merged ?

**Comment by AkechiShiro** [comment]
Oh sorry thought this was a PR

**Comment by swaylortift** [comment]
Is work being done on this? I agree current output options are not very useful Thank you!!!

**Comment by swaylortift** [comment]
Oops nvm! Turns out the tool mentioned by OP (https://github.com/bepaald/signalbackup-tools) does this already. Thanks anyway!

**Comment by tbvdm** [comment]
This is still a to-do item. If people want to help, PRs are welcome.
