### ISSUE TITLE
Signal path differnt for snap-based installation (easy fix, might be included in README.md)

### ISSUE THREAD

**Issue by widmi** [tbvdm/sigtop#4]
Hi! Your app saved me so much troubles, thank you!
For snap-based installation on Ubuntu, the storage path will be different. But a simple
`ln -s /home/$USER/snap/signal-desktop/current/.config/Signal Signal`
in the terminal does the trick :)
Maybe this could be included in README.md.
Thank you again for this super convenient tool!
Best wishes

**Comment by tbvdm** [comment]
> Hi! Your app saved me so much troubles, thank you!

You're welcome!

> For snap-based installation on Ubuntu, the storage path will be different. But a simple
> `ln -s /home/$USER/snap/signal-desktop/current/.config/Signal Signal`
> in the terminal does the trick :)
> Maybe this could be included in README.md.

It would be even better if sigtop would try the snap directory if the default directory doesn't exist, without the user having to do anything. I have just pushed a commit for this. Thanks!
