### ISSUE TITLE
Program detected as a virus

### ISSUE THREAD

**Issue by radiophonic** [tbvdm/sigtop#40]
Not sure if you're aware of this but the binary is being detected as a virus (Wacatac.B!ml)

If it's a false-positive, carry on and thanks.

**Comment by tbvdm** [comment]
It most likely is a false positive. It's a common issue for Go programs, unfortunately. The [Go FAQ](https://go.dev/doc/faq#virus) has a few words about it.

If you prefer, you can build sigtop from source. The instructions are in the README.
