### ISSUE TITLE
"att -M" command throws error "utimes: unsupported flag"

### ISSUE THREAD

**Issue by virtuallyvlad** [tbvdm/sigtop#41]
When running `sigtop att attachments`, sigtop runs mostly fine.  But when I run `sigtop att -M attachments-M` it throws a ton of "sigtop.exe: utimes: unsupported flag" errors.  The attachments still export the same, but the modified timestamps aren't changed and those errors are thrown.

**Comment by virtuallyvlad** [comment]
It still didn't work for me, but now it gives the error "sigtop.exe: utimes <filename>: The system cannot find the file specified."

Without `-M`, these errors don't appear.

**Comment by tbvdm** [comment]
Could you try again?

**Comment by virtuallyvlad** [comment]
Yes, it now works (with v0.9.1).  Those errors no longer appear and the modified timestamps are changed correctly. Thanks a bunch!

**Comment by tbvdm** [comment]
Great, thanks for confirming!
