### ISSUE TITLE
Emoji in chat title

### ISSUE THREAD

**Issue by luciajajcay** [tbvdm/sigtop#42]
Hi, is there any way to export a group chat with an emoji in the title? None of the things I've tried have worked.

**Comment by tbvdm** [comment]
What have you tried, what errors are you getting, and what OS are you using?

**Comment by luciajajcay** [comment]
I've tried copy-pasting the emoji (from Signal or from emojipedia), using the name of the emoji instead of the emoji itself, different conversation selectors (phone number of a member of the group chat, or regex, instead of the name of the chat).

Keep getting this error:
`sigtop: open Signal_exports/sigtop/messages/chat_name (group).txt: illegal byte sequence
`
(I've replaced the actual name of the chat with 'chat_name' here...)

On iOS.

**Comment by tbvdm** [comment]
Are you running sigtop on iOS? Or did you mean macOS? I'm going to assume the latter.

The problem is that sigtop cannot create a file for your group chat because the filename contains an "illegal byte sequence" (according to macOS). I suspect this is because macOS imposes certain (questionable) restrictions on filenames.

Could you try this:

```
git clone -b test https://github.com/tbvdm/sigtop.git
cd sigtop
go build
./sigtop msg msg
```

Please show me the output of the sigtop command. Feel free to redact filenames. The output will look something like this:

```
sigtop: open msg/chat_name (group).txt: illegal byte sequence
sigtop: retrying: converting to NFD
sigtop: open msg/chat_name (group).txt: illegal byte sequence
sigtop: retrying: removing emojis
sigtop: open msg/chat_name (group).txt: illegal byte sequence
sigtop: retrying: converting to NFD and removing emojis
```

**Comment by luciajajcay** [comment]
macOS, sorry :)

That worked! Here's the output:

```
sigtop: open msg/chat_name (group).txt: illegal byte sequence
sigtop: retrying: converting to NFD
sigtop: open msg/chat_name (group).txt: illegal byte sequence
sigtop: retrying: removing emojis
```

**Comment by tbvdm** [comment]
Great, thanks. One more thing: could you look up the emoji on Emojipedia again and tell me in which Unicode version it was introduced? I expect it is a version after 9.0.

**Comment by luciajajcay** [comment]
15.0, yep. Thanks for your help!

**Comment by tbvdm** [comment]
Thanks. So it's safe to say that Apple's filename restrictions are to blame. I'll have to figure out a good way to address this in sigtop.
