### ISSUE TITLE
Attachments decryption

### ISSUE THREAD

**Issue by flatz** [tbvdm/sigtop#49]
Hello @tbvdm,

I've tried to export attachments today and looks like they looks encrypted. Then I've looked into Signal's commits and looks like there is a new storage system for attachments that use another encryption scheme. Can you please check? https://github.com/signalapp/Signal-Desktop/commit/28664a606f1fd8e912ceca7907de544592a8f938 (see these ones:  **generateKeys**  **decryptAttachmentV2ToSink**  **encryptAttachmentV2ToDisk**).

**Comment by tbvdm** [comment]
Thanks. I think this should work now.
