### ISSUE TITLE
feature suggestion: export-messages and export-attatchments for only one friend

### ISSUE THREAD

**Issue by FalafelGood** [tbvdm/sigtop#5]
Hi, great project, thanks for making this.

It'd be great to have improved functionality on export-messages and export-attachments so that you can backup a conversation with only one friend. Is this something that's feasible?

**Comment by tbvdm** [comment]
Hi. Yes, definitely. I'm working on this. It should be ready soon(ish).

**Comment by tbvdm** [comment]
I still plan to add this feature, but it won't be ready so "soon(ish)" after all.

Fortunately, however, sigtop now exports messages and attachments separately per conversation. So in your case, you can just run `export-messages` or `export-attachments`, keep the conversation you're interested in and delete the rest.
