### ISSUE TITLE
Doesn't account for multiple users with same name

### ISSUE THREAD

**Issue by micr0-dev** [tbvdm/sigtop#53]
If there are 2 people with the same name then bad things happen as the file with that name already exists. Either a discriminator must be given, Niko\ (2).txt. Or something else should be used for labeling the files (userID?)
```
~/go/bin/sigtop export-messages -k ~/passfile messages
sigtop: open Niko.txt: file exists
```

**Comment by tbvdm** [comment]
Thanks for reporting this and for the PR. I've pushed a commit that should fix your issue in a different way. Could you give it a try?
