### ISSUE TITLE
Cannot Find Key: "sigtop: cannot decrypt database key: cannot find encryption key"

### ISSUE THREAD

**Issue by piercegwang** [tbvdm/sigtop#56]
OS: NixOS (Custom build of the latest version of sigtop, 0.15.0)
Problem: No matter what command I run, I receive a `sigtop: cannot decrypt database key: cannot find encryption key` error.

Things I've tried:

- giving `sigtop` my Signal directory directly (`~/.config/Signal` and `/home/user/.config/Signal`)
- running various commands (`check-database`, `export-messages`, etc.)
- giving it a keyfile with `-k`, which did not work even though the option `-k` is listed in some of the usage examples 
  - (aka `usage: sigtop export-messages [-i] [-c conversation] [-d signal-directory] [-f format] [-k [system:]keyfile] [-s interval] [directory]`)

I see that other people have posted issues unrelated to this, and I assume that at some level this program must work... so, my only conclusion is that I'm doing something stupid or missing something. But, I can't for the life of me figure out what that is. Any help would be greatly appreciated!

**Comment by olewales** [comment]
Just installed sigtop for the first time and encountered the same issue.
Version: sigtop@v0.15.1-0.20240913183615-8909429fc593
Signal desktop version: 7.21.0

**Comment by tbvdm** [comment]
What desktop environment are you using?

How did you generate the keyfile, and what is the command you used to pass the keyfile to sigtop?

**Comment by piercegwang** [comment]
Thanks for replying! I'm using KDE Plasma 6.

For the keyfile, I didn't know I had to generate one. From what I could tell from the sigtop man page, it just requires the directory. None of the example commands passed a keyfile, so I was sort of just guessing along the way. These are the commands I tried:

- `sigtop export-key -d ~/.config/Signal/ key.json`
  - `sigtop: cannot get encryption key: cannot find encryption key`
  - I've also tried variations of this, with different kinds of files, writing to standard output (by leaving the file blank), removing the `-d` argument, etc. Always the same output though...
- `sigtop db -d /home/alice/.config/Signal signal.db`
  - Returns: `sigtop: cannot decrypt database key: cannot find encryption key`
- `sigtop export-messages -d /home/alice/.config/Signal messages`
  - Returns: `sigtop: cannot decrypt database key: cannot find encryption key`

What other commands should I run to get the encryption key? Are there documented hoops I have to jump through currently due to weird signal encryption things? Thanks for your help again.

**Comment by tbvdm** [comment]
I understand your confusion. KDE support in sigtop is subpar currently. The documentation is not completely up to date either.

To generate a keyfile for KDE, run:

```
kwallet-query -l kdewallet -f "Chromium Keys" -r "Chromium Safe Storage" >keyfile
```

Then use the `-k` option to pass the keyfile to sigtop. For example:

```
sigtop export-messages -k keyfile messages
```

You can also pipe the `kwallet-query` output directly to sigtop if you prefer. For example:

```
kwallet-query -l kdewallet -f "Chromium Keys" -r "Chromium Safe Storage" | sigtop export-messages -k - messages
```

**Comment by piercegwang** [comment]
Fantastic. Finally got around to testing this, and it works like a charm. Would it be helpful if made a pull request to add this info to the readme?

**Comment by tbvdm** [comment]
sigtop is now able to get the encryption key from KWallet. You no longer have to run `kwallet-query` and provide a keyfile.
