### ISSUE TITLE
How to use the exported kay to connect with sqllite

### ISSUE THREAD

**Issue by barsifedron** [tbvdm/sigtop#58]
Hi.

Probbaly the wrong spot to write this question and a bit out of scope with the project.

But once one used 
`sigtop export-key`

Is there a way to use thsi key with DB browser for sql lite?

If yes, would you have any tips on how to do that?

**Comment by tbvdm** [comment]
> Probbaly the wrong spot to write this question and a bit out of scope with the project.

It's a good question and this is the right place to ask.

> Is there a way to use thsi key with DB browser for sql lite?

No, you need a different key for that. Currently `export-key` is intended to be used in conjunction with the `-k` option of the other commands. But I'll add an option to export the database key itself, which is the key you want.

**Comment by barsifedron** [comment]
Thanks a lot!

**Comment by tbvdm** [comment]
You can now run `sigtop export-key -D` to get the database key.
