### ISSUE TITLE
file is not a database

### ISSUE THREAD

**Issue by jathri** [tbvdm/sigtop#59]
Hello,
tried to run (windows):
sigtop export-messages -d C:\Users\someUser\AppData\Roaming\Signal\ messages
And got:
ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
ERROR CORE sqlcipher_codec_ctx_set_error 1
sigtop.exe: cannot verify key: cannot execute SQL statement: file is not a database
Can something be done?

NOTE: Signal desktop app seems to work correctly. All messages are synced without problems (between phone and desktop).

**Comment by tbvdm** [comment]
I see that you are using the -d option. Are you trying to export messages for another user?

**Comment by jathri** [comment]
No. And have success with different approach - generating html from android backup file. So closing here for now. Will reopen if needed. Thank you for comment.
