### ISSUE TITLE
precise reference to attachments in messages

### ISSUE THREAD

**Issue by aa755** [tbvdm/sigtop#6]
here is a sample entry in my messages.txt generated using 
`./sigtop export-messages messages.txt`:

```
Conversation: Gunjan
Type: outgoing
To: Gunjan
Sent: Sat, 9 Apr 2022 22:12:15 -0400
Attachment: image.png (image/png, 140855 bytes)
```
how do I figure out which image this `image.png` is referring to? the `image.png` in the attachments directory is not the one that I sent in this message. But the attachments directory has many files of the form image-n.png for n 1,2,3...50 and I guess the correct image is one of them.
Is there a way to have the messages export precisely specify which image/document in attachments is being referred to?

**Comment by tbvdm** [comment]
> I guess the correct image is one of them.

Yes. If you have multiple attachments with the same filename, sigtop adds a sequence number.

> Is there a way to have the messages export precisely specify which image/document in attachments is being referred to?

That's an interesting one. Currently there isn't. I could add an option to set the modification time of attachment files to the time they were sent. Would that help you?

For now, as a workaround, you could try to identify the right attachment file by looking at the file size (140855 bytes in your case).
