### ISSUE TITLE
export-messages: invalid option -- 's'

### ISSUE THREAD

**Issue by corbolais** [tbvdm/sigtop#60]
Calling sigtop with msg -s <TIMEINTERVAL> has been working nicely for the last years. Thank you for this tool!

As of recently, I got garbeled file contents and therefore upgraded to HEAD. But then:

```
sigtop export-messages -s 2024-07-09T23:59:59, ./signal-bkp/files/
export-messages: invalid option -- 's'
```

Same for attachements.

Any hint appreciated.

Thank you.

**Comment by tbvdm** [comment]
I think you're still on the old portable branch. Please switch to the master branch. Also note that sigtop has been rewritten in Go, so dependencies and build instructions have changed.

**Comment by corbolais** [comment]
Thanks for your reply.

> I think you're still on the old portable branch. Please switch to the master branch. Also note that sigtop has been rewritten in Go, so dependencies and build instructions have changed.

```
✔ ~/repo/sigtop [master] 
13:17 $ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

Any other ideas?

**Comment by tbvdm** [comment]
Somehow you must be running a very old version of sigtop. The error message you pasted has a format that would be used by the old C implementation of sigtop; it could not have come from the current Go implementation.

**Comment by corbolais** [comment]
Thx. Must've been a PEBKAC. Ran install again and this time it worked. Last time it installed a binary with correct timestamp but somehow was the an outdated version. Strange enough.
