### ISSUE TITLE
Add support for Signal Beta in safe storage

### ISSUE THREAD

**Issue by jsutlovic** [tbvdm/sigtop#62]
Hi there,

`sigtop` currently hardcodes `"Signal"` as the app name for safe storage, but at least on MacOS, Signal and Signal Beta use a different safe storage:
<img width="203" alt="Screenshot 2024-10-25 at 4 56 08 PM" src="https://github.com/user-attachments/assets/a65a373b-94ec-45e2-b482-628e39e419da">

I've fixed this in my branch [here](https://github.com/tbvdm/sigtop/compare/master...jsutlovic:sigtop:signal-beta-support), I can create a PR if you'd like.

**Comment by tbvdm** [comment]
Hi. Thank you very much! Your changes look great! However, I think a better approach is to introduce a `-B` flag that should change the app name to "Signal Beta" and also adjust the Signal directory (unless already specified with `-d`). I don't know if you're willing to adjust your fix, but if you are, that would be great!

**Comment by jsutlovic** [comment]
I did initially consider that option but I wasn't sure if all platforms used the same pattern for Signal Beta. I should be able to update the branch to use a `-B` flag instead, though, I'll update once it's ready.

**Comment by tbvdm** [comment]
> I did initially consider that option but I wasn't sure if all platforms used the same pattern for Signal Beta.

Ah, I see. Yes, it's the same pattern as far as I know.

> I'll update once it's ready.

Great!

**Comment by jsutlovic** [comment]
Hi @tbvdm, I've updated the branch and was able to test/validate again, it seems to work as expected.

**Comment by tbvdm** [comment]
Looks good! Could you create a PR?
