### ISSUE TITLE
sigtop check Error: cannot verify key: cannot execute SQL statement: file is not a database

### ISSUE THREAD

**Issue by gh2023-aesun** [tbvdm/sigtop#63]
I have the debian Signal Desktop installed (sudo apt list --installed | grep signal > signal-desktop/xenial,now 7.30.0 amd64 [installed]) on a Pop!_OS 22.04 LTS Gnome 42.9 computer.  The Signal Desktop application is working fine.

I've also had a flatpak version of Signal installed in the past, but was having issues so I uninstalled it for the .deb version.  The config folder ($HOME/.var/app/org.signal.Signal/config/Signal) is still on my computer.

I followed the install instructions and received no errors.

When I execute any of the following commands, either with Signal Desktop running or not:
`sigtop check`
`sigtop check -d $HOME/.config/Signal`
`sigtop check -d $HOME/.var/app/org.signal.Signal/config/Signal`

I get this error message
`sigtop: cannot verify key: cannot execute SQL statement: file is not a database`

I've tried uninstalling/re-installing (rm $HOME/go/bin/sigtop  && go install github.com/tbvdm/sigtop@master), with the same outcome.

Are there any extra steps I need do to make this work?

For example, in this post [here](https://github.com/tbvdm/sigtop/issues/48#issuecomment-2256050015) there is discussion about fetching the encryption password.

So I installed secret-tool and ran sigtool but it yielded the following: 

`sudo apt install libsecret-tools`

`secret-tool lookup application Signal | sigtop export-messages -p - messages`

`sigtop: -p: invalid option`
`secret-tool: couldn't write password: Broken pipe`

Any thoughts?

**Comment by tbvdm** [comment]
What is the output of `command -v sigtop`? And what happens when you run `~/go/bin/sigtop check`?

**Comment by gh2023-aesun** [comment]
`command -v sigtop` > `~/bin/sigtop`

`~/go/bin/sigtop check` > null response

**Comment by tbvdm** [comment]
> Thank you so much, I have to execute with ~/go/bin/sigtop instead of sigtop.

You should remove `~/bin/sigtop` (which apparently is an old version of sigtop). Then run `command -v sigtop` again. If it outputs `~/go/bin/sigtop`, you can simply type `sigtop` to run sigtop.

> Regarding the old flatpak database shown above, is there anyway to circumvent `sigtop: cannot decrypt database key: invalid padding size` to see what data is in there?

That depends. I think the .deb version of Signal will have overwritten the encryption key used by the Flatpak version of Signal. If so, I fear it will be impossible to decrypt to Flatpak database (unless you are able to recover the Flatpak encryption key, e.g. through backups).

**Comment by gh2023-aesun** [comment]
I cleaned up my install, as you suggested and will try getting the flatpak db data from a backup.

Thank you again for being so responsive and creating such a great utility.
