### ISSUE TITLE
Feature Request: Add Support for UUID-based Conversation Selector

### ISSUE THREAD

**Issue by Judx** [tbvdm/sigtop#65]
Feature Request: Add Support for UUID-based Conversation Selector

### Problem
It's hard to differentiate between conversations with the same name. Selecting by regex can also lead to incorrect or partial matches. This makes it difficult to reliably select conversation. 

### Solution
Add support for selecting conversations using their unique identifiers (UUIDs). This would allow users to specify conversations with precision, avoiding conflicts caused by duplicate names or regex mismatches.

### Implementation
Extend the `-c` option in commands like `export-messages`, `export-attachments`, and `export-avatars` to accept `uuid:<id>` as a valid selector.

### Examples
```sh
 sigtop msg -c uuid:123e4567-e89b-12d3-a456-426614174000
```

**Comment by tbvdm** [comment]
Good idea. I chose a slightly different syntax for consistency: `-c :<uuid>`. For example:

```
sigtop msg -c :123e4567-e89b-12d3-a456-426614174000
```

**Comment by Judx** [comment]
Thank you @tbvdm for adding this feature! It works reportedly for 1-on-1 conversations. However, after testing I’ve noticed that it doesn’t seem to work for group chats. Group chats do not have servideId, instead they are identified with groupId. Is there any chance this could be addressed?

Thanks again for your great work!

**Comment by tbvdm** [comment]
Group IDs should now work, too.

**Comment by Judx** [comment]
Confirmed, the Group IDs works now. Thank you for the support and great work @tbvdm!
