### ISSUE TITLE
[BUG]: unexpected behavior when running sigtop through a bat file

### ISSUE THREAD

**Issue by ghost** [tbvdm/sigtop#67]
Hi! Thanks for making sigtop 😄 

I'm trying to automate sigtop to daily export messages and attachements to specific folders. Manually it works just fine, but when using a bat file it will loop the contents of the bat file indefinitely:

With the line: `start "" sigtop export-attachments -iM -c "Test" -d "C:\Signal-Data" "C:\Test"`, an infinite amount of cmd prompts will spawn very quickly to the point of requiring physically turning off the PC.

With the line: `sigtop export-attachments -iM -c "Test" -d "C:\Signal-Data" "C:\Test"`, the same line will loop infinitely at the same speed in the same cmd window, not spawning new ones.

Any idea why this is happening? I'm on Windows 10 Pro btw.

Thank you!

**Comment by tbvdm** [comment]
It looks like the batch file is executing itself. Is the batch file also named `sigtop`? Try using the full path to the sigtop program, e.g.

```
start "" c:\users\you\sigtop.exe ...
```
