### ISSUE TITLE
Error on export: sigtop: Cannot parse quote JSON data

### ISSUE THREAD

**Issue by MichaelKuz** [tbvdm/sigtop#9]
On MacOS, installed with:

brew install --HEAD tbvdm/tap/sigtop

Error:
$ sigtop export-messages messages
sigtop: Cannot parse quote JSON data

$ sigtop export-attachments attachments
sigtop: Cannot parse quote JSON data

Messages and attachments *are* successfully exported for most threads and it seems like the error is related to one contact/thread. 

[As discussed on https://github.com/tbvdm/sigtop/issues/8, the latest version of sigtop still causes this error for me]

**Comment by MichaelKuz** [comment]
Unclear if this is helpful to you, but I followed the first instruction in issue #8 and the err file has the following contents: 

`sigtop: Quote without id
sigtop: Cannot parse quote JSON data
`

**Comment by tbvdm** [comment]
Thanks for trying that.

Could you update the test branch and then run:

```
PKG_CONFIG_PATH=$(brew --prefix)/opt/libressl/lib/pkgconfig gmake clean all
rm -f err msg
./sigtop msg msg 2>err
```

First, please run the following command and then show the contents of the `err2` file.

```
grep ^sigtop err >err2
```

Second, please take a look at the `err` file. Each `Quote without id` warning is followed by the JSON data of the message that caused the warning. Would you mind taking a look at those messages? Do they look like regular messages or can you spot anything that seems suspicious?

Thanks!

**Comment by MichaelKuz** [comment]
I'm a bit of a novice here, so I'm not sure I updated the test branch correctly. Would you please provide instructions on the best command to run for that? 

When I tried on my own and then followed the instructions in your latest message, I did not see the JSON data of the message in either err file.

**Comment by tbvdm** [comment]
In this case, `git pull` would have been enough. But I don't know what state your repo is in now, so perhaps it's best to clone it afresh. Delete your old repo (or move it out of the way) and then run:

```
git clone -b test https://github.com/tbvdm/sigtop.git
cd sigtop
```

Then try again. If it still doesn't work, let me know!

**Comment by MichaelKuz** [comment]
Ah, ok. Yes, I must have screwed up my repo somehow. Thanks for being so patient with me. 

Following your instructions, I'm now able to see the following errors, followed by the JSON from the message in question (not pasted here):

```
sigtop: Quote without id
sigtop: Message has type outgoing
sigtop: Message has body (69 bytes)
sigtop: Message does not have errors
sigtop: Quote does not have author
sigtop: Quote has authorUuid (36 bytes)
sigtop: Quote has text (109 bytes)
sigtop: Quote has attachments (2 bytes)
```

As indicated by your debug messages, and in response to your question upthread, I can report that the message and quote text both look fine/unsuspicious to the naked eye.

Unlike the first error message, I *do* see an id nested in the "quote" section of the JSON - it is present and is a 13-character integer.

**Comment by tbvdm** [comment]
Is that 13-character integer inside quotation marks? That is, do you see `"id": 123` or `"id": "123"`?

If it's the latter, then that must be the cause. sigtop expects a number, not a string.

**Comment by MichaelKuz** [comment]
It's the latter

**Comment by MichaelKuz** [comment]
Thank you, it looks like that worked!

I also get the error when trying to export attachments – the same user who has the offending quote message does not show up in the attachments folder. I'm not sure if it's an unrelated problem due to a bad attachment, or due to the same quote issue. Is there an analogous command I can run to find out?

**Comment by tbvdm** [comment]
> Thank you, it looks like that worked!

Great! Just to be sure, could you confirm that `err2` is an empty file?

> I also get the error when trying to export attachments – the same user who has the offending quote message does not show up in the attachments folder. I'm not sure if it's an unrelated problem due to a bad attachment, or due to the same quote issue. Is there an analogous command I can run to find out?

Yes, it is (or rather was) the same problem. If you run the following command, you should find all attachments, including those that were missing before, in the `att` directory:

```
./sigtop att att
```

**Comment by MichaelKuz** [comment]
Confirming err2 is empty and that I was able to find all of
the attachments.

Thanks again for the help, you've been very clear & kind. Hope I can return
the favor one day.

**Comment by tbvdm** [comment]
Excellent! Thank you for reporting!
